### ISSUE TITLE
[BUG] Bluewallet: name of container in docker-compose file doesn't match with the actual name of the container

### ISSUE THREAD

**Issue by MisterCyp** [getumbrel/umbrel-apps#1039]
Hello,

I tried to install BlueWallet Lightning on my umbrel node and it never worked (installation stuck on starting process)
When I investigate I discover that the hostname in the docker-compose of bluewallet doesn't match with the actual name of the container.

bluewallet/docker-compose.yml :
```

services:
  app_proxy:
    environment:
      APP_HOST: bluewallet_lndhub_1
      APP_PORT: 3008
      PROXY_AUTH_ADD: "false"
```

The name oh the container on my PC: `bluewallet-lndhub-1`

When I changed the name in the docker-compose.yml, it has worked.

I'm the only one having this problem ?
