### ISSUE TITLE
[Feature] FreshRSS is requiring umbrel authentication

### ISSUE THREAD

**Issue by jjmmbb** [getumbrel/umbrel-apps#1691]
There is any special reason to access FreshRSS requiring umbrel authentication before? Many other important tools just doesn't require. Is it important to have it requiring that? Would it be wrong to think that it would not need this authentication, since there is a login/password to access it?

**Comment by johnpc** [comment]
This is one of my biggest frustrations with umbrel in general. You can work around this by updating `~/umbrel/app-data/freshrss/docker-compose.yml` to add `PROXY_AUTH_ADD: "false"`, like this:

```
umbrel@umbrel:~$ cat ~/umbrel/app-data/freshrss/docker-compose.yml
version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: freshrss_server_1
      APP_PORT: 80
      PROXY_AUTH_WHITELIST: /api/*
      PROXY_AUTH_ADD: 'false'
    container_name: freshrss_app_proxy_1
  server:
    image: >-
      linuxserver/freshrss:1.24.3@sha256:15212add8c05130346c5fb465b99b72ec18923a5d9fd6044d28e9ebe13241f4d
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config
    container_name: freshrss_server_1
```

You can then stop/start freshrss and umbrel authentication will stop. However, your update _will_ be overwritten whenever you update to a new version of freshrss, so you'll have to add that field manually again.

In my opinion umbrel should come up with a way for users to enable/disable umbrel authentication in a more persistent way via the ui, since there are several apps I want to expose without authentication. But right now this is the only way.
