### ISSUE TITLE
Application Request: TeslaMate

### ISSUE THREAD

**Issue by sashazykov** [getumbrel/umbrel-apps#481]
https://docs.teslamate.org/docs/installation/docker

**Comment by mroxso** [comment]
I like that!
I think I will work on trying to integrate it.

You can see the status (and test it) here:
https://github.com/mroxso/pluto-umbrel-community-app-store

**Comment by mroxso** [comment]
But it is my first Umbrel App.
And as far as I can see TeslaMate uses 2 Frontends:
- for setting up on port 4000
- for grafana dashboard on port 3000

anybody an idea how to realize that for umbrel?

**Comment by sashazykov** [comment]
I now have teslamate running alonside umbrel and it works fine.

Regarding two ports, you can just link Telsamate UI from Umbrel and there is a link to Grafana from the UI itself.

**Comment by mroxso** [comment]
I think the most part is done.
Only the secrets are the "bad" thing right now.
Everything works.
I tested it with my Umbrel Node

**Comment by sashazykov** [comment]
I would suggest you to run it under user and move volumes to the umbrel apps data directory. Here is docker-compose I use:

```yml
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    user: "1000:1000"
    restart: always
    environment:
      - ENCRYPTION_KEY=key
      - DATABASE_USER=teslamate
      - DATABASE_PASS=dbpass
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
    user: "1000:1000"
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=teslamate
    volumes:
      - ./data/teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    user: "1000:1000"
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=dbpass
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - ./data/teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    user: "1000:1000"
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ./data/mosquitto-conf:/mosquitto/config
      - ./data/mosquitto-data:/mosquitto/data
```
