### ISSUE TITLE
Proxy redirection to different internal port

### ISSUE THREAD

**Issue by zigazajc007** [getumbrel/umbrel-apps#88]
How can I tell the proxy to redirect traffic from external port 5050 to internal port 80?
```yml
PORTS                                                 NAMES
9050-9051/tcp, 29050-29051/tcp                        passky-server_tor_server_1
0.0.0.0:5050->5050/tcp, :::5050->5050/tcp             passky-server_app_proxy_1
3306/tcp                                              passky-server_database_1
80/tcp                                                passky-server_api_1
```

This does not work:
```yml
  app_proxy:
    environment:
      APP_HOST: $APP_PASSKY_SERVER_IP
      APP_PORT: 5050:80
      PROXY_AUTH_ADD: "false"
```

app_proxy seems to be required otherwise tor will crash. But with proxy I can't use something like this: 
```yml
ports:
  - 5050:80
```

I also don't want to change external port 80 in a docker image as this project is deployed on multiple one click installers, so I really don't want to make it special just for Umbrel.

Thanks
