### ISSUE TITLE
App Request: Planka (kanban board)

### ISSUE THREAD

**Issue by johnpc** [getumbrel/umbrel-apps#925]
Planka is a self-hosted kanban board application that I use. Think self-hosted Trello. See https://planka.app for a demo / more information.

It is already dockerized (see https://github.com/plankanban/planka/blob/master/docker-compose.yml and [installation documentation](https://docs.planka.cloud/docs/installation/docker/production_version/)).

**Comment by smolgrrr** [comment]
Thanks for the suggestion.
I will check this out now :)

**Comment by w0aw** [comment]
hey @smolgrrr, it would be better if try to add plane instead of this one. checkout [plane](https://plane.so)

i have tried to run it locally but there is an routing issue. (they have seprate ui & apis container) and paths starting with /api and /space need to be routed on diff containers, i dont know how can i resolve this.

in their official docs they also provide another container called plane-proxy but it support to be run on host OS port 80 and we cant have multiple proxies together.

```yaml
host: {{ .Values.ingress.appHost }}

http:
  paths:
    - backend:
        service:
          port: 3000
          name: {{ .Release.Name }}-web
        path: /
        pathType: Prefix
    - backend:
        service:
          port: 8000
          name: {{ .Release.Name }}-api
        path: /api
        pathType: Prefix
    - backend:
        service:
          port: 3000
          name: {{ .Release.Name }}-space
        path: /spaces
        pathType: Prefix
    - backend:
        service:
          port: 9000
          name: {{ .Release.Name }}-minio
        path: /{{ .Values.env.docstore_bucket }}
        pathType: Prefix
      {{- if .Values.minio.local_setup }}
```
